import { Product } from '@/types/product';

const UNSPLASH = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&q=80`;

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Linen Summer Kurta',
    brand: 'FabIndia',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    images: [
      UNSPLASH('photo-1610030469983-98e550d6193c'),
      UNSPLASH('photo-1618354691373-d851c5c3a990'),
    ],
    category: 'Ethnic Wear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Beige', hex: '#F5F0E8' }, { name: 'Blue', hex: '#4A90D9' }],
    rating: 4.5,
    reviewCount: 238,
    badges: ['trending-in-size', 'price-dropped'],
    stock: 8,
    description: 'Breathable linen kurta perfect for casual summer days. Hand-block printed with natural dyes.',
    tags: ['summer', 'casual', 'ethnic', 'linen'],
  },
  {
    id: 'p2',
    name: 'Floral Midi Dress',
    brand: 'Zara',
    price: 2499,
    originalPrice: 3499,
    discount: 28,
    images: [
      UNSPLASH('photo-1515372039744-b8f02a3ae446'),
      UNSPLASH('photo-1539109136881-3be0616acf4b'),
    ],
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Rose', hex: '#FFB6C1' }, { name: 'Yellow', hex: '#FFD700' }],
    rating: 4.7,
    reviewCount: 412,
    badges: ['matches-style', 'low-stock'],
    stock: 3,
    description: 'Elegant floral midi dress with a flowy silhouette. Perfect for date nights and brunches.',
    tags: ['floral', 'dress', 'date-night', 'festive'],
  },
  {
    id: 'p3',
    name: 'Slim Fit Chinos',
    brand: 'H&M',
    price: 1799,
    originalPrice: 2299,
    discount: 21,
    images: [
      UNSPLASH('photo-1594938298603-c8148c4dae35'),
      UNSPLASH('photo-1602810318383-e386cc2a3ccf'),
    ],
    category: 'Bottoms',
    sizes: ['28', '30', '32', '34', '36'],
    colors: [{ name: 'Khaki', hex: '#C3B091' }, { name: 'Navy', hex: '#1C2F5A' }, { name: 'Olive', hex: '#556B2F' }],
    rating: 4.3,
    reviewCount: 187,
    badges: ['trending-in-size'],
    stock: 15,
    description: 'Versatile slim fit chinos that work for both office and casual settings.',
    tags: ['office', 'casual', 'chinos', 'bottoms'],
  },
  {
    id: 'p4',
    name: 'Embroidered Blouse',
    brand: 'W for Woman',
    price: 999,
    originalPrice: 1499,
    discount: 33,
    images: [
      UNSPLASH('photo-1591369822096-ffd140ec948f'),
      UNSPLASH('photo-1562157873-818bc0726f68'),
    ],
    category: 'Tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Pink', hex: '#FFB6C1' }, { name: 'Mint', hex: '#98FF98' }, { name: 'White', hex: '#FFFFFF' }],
    rating: 4.6,
    reviewCount: 325,
    badges: ['matches-style', 'price-dropped'],
    stock: 20,
    description: 'Delicate embroidered blouse with mirror work. A festive staple for every wardrobe.',
    tags: ['festive', 'ethnic', 'blouse', 'embroidery'],
  },
  {
    id: 'p5',
    name: 'Performance Running Tee',
    brand: 'Nike',
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    images: [
      UNSPLASH('photo-1556821840-3a63f15732ce'),
      UNSPLASH('photo-1521572163474-6864f9cf17ab'),
    ],
    category: 'Sportswear',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }, { name: 'Red', hex: '#FF0000' }],
    rating: 4.8,
    reviewCount: 562,
    badges: ['trending-in-size'],
    stock: 30,
    description: 'Moisture-wicking performance tee with Dri-FIT technology. Ideal for intense workouts.',
    tags: ['gym', 'sport', 'running', 'performance'],
  },
  {
    id: 'p6',
    name: 'Silk Saree',
    brand: 'Taneira',
    price: 8999,
    originalPrice: 12999,
    discount: 30,
    images: [
      UNSPLASH('photo-1610030020586-05f877ef1e4a'),
      UNSPLASH('photo-1583391733956-3750e0ff4e8b'),
    ],
    category: 'Ethnic Wear',
    sizes: ['Free Size'],
    colors: [{ name: 'Gold', hex: '#FFD700' }, { name: 'Maroon', hex: '#800000' }, { name: 'Green', hex: '#006400' }],
    rating: 4.9,
    reviewCount: 94,
    badges: ['low-stock', 'matches-style'],
    stock: 2,
    description: 'Handwoven Kanjivaram silk saree with zari border. A timeless piece for weddings and celebrations.',
    tags: ['festive', 'wedding', 'silk', 'saree', 'ethnic'],
  },
  {
    id: 'p7',
    name: 'Denim Jacket',
    brand: "Levi's",
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    images: [
      UNSPLASH('photo-1551537482-f2075a1d41f2'),
      UNSPLASH('photo-1578932750294-f5075e85f44a'),
    ],
    category: 'Outerwear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Blue', hex: '#4A90D9' }, { name: 'Black', hex: '#000000' }],
    rating: 4.6,
    reviewCount: 310,
    badges: ['price-dropped'],
    stock: 12,
    description: 'Classic denim jacket with a modern slim fit. A wardrobe essential for travel and casual outings.',
    tags: ['casual', 'travel', 'denim', 'jacket'],
  },
  {
    id: 'p8',
    name: 'Pleated Palazzo Set',
    brand: 'Global Desi',
    price: 2199,
    originalPrice: 2999,
    discount: 26,
    images: [
      UNSPLASH('photo-1583744946564-b52ac1c389c8'),
      UNSPLASH('photo-1594938298603-c8148c4dae35'),
    ],
    category: 'Co-ords',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Teal', hex: '#008080' }, { name: 'Rust', hex: '#B7410E' }],
    rating: 4.4,
    reviewCount: 156,
    badges: ['matches-style', 'trending-in-size'],
    stock: 7,
    description: 'Breezy palazzo set with block prints. Perfect for a day out or a casual office look.',
    tags: ['casual', 'ethnic', 'palazzo', 'co-ords'],
  },
  {
    id: 'p9',
    name: 'Formal Oxford Shirt',
    brand: 'Van Heusen',
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    images: [
      UNSPLASH('photo-1598033129183-c4f50c736f10'),
      UNSPLASH('photo-1603252109303-2751441dd157'),
    ],
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Blue', hex: '#4A90D9' }, { name: 'Grey', hex: '#808080' }],
    rating: 4.5,
    reviewCount: 289,
    badges: ['trending-in-size'],
    stock: 25,
    description: 'Crisp Oxford shirt with wrinkle-resistant fabric. Office-ready in minutes.',
    tags: ['office', 'formal', 'shirt', 'work'],
  },
  {
    id: 'p10',
    name: 'Yoga Slim Leggings',
    brand: 'Decathlon',
    price: 799,
    originalPrice: 1199,
    discount: 33,
    images: [
      UNSPLASH('photo-1506629082955-511b1aa562c8'),
      UNSPLASH('photo-1518611012118-696072aa579a'),
    ],
    category: 'Activewear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#1C2F5A' }, { name: 'Coral', hex: '#FF6B6B' }],
    rating: 4.7,
    reviewCount: 478,
    badges: ['price-dropped', 'trending-in-size'],
    stock: 40,
    description: 'High-waist yoga leggings with 4-way stretch and hidden pocket. Perfect for yoga and gym.',
    tags: ['gym', 'yoga', 'activewear', 'leggings'],
  },
  {
    id: 'p11',
    name: 'Leather Tote Bag',
    brand: 'Hidesign',
    price: 4999,
    originalPrice: 6999,
    discount: 28,
    images: [
      UNSPLASH('photo-1553062407-98eeb64c6a62'),
      UNSPLASH('photo-1548036328-c9fa89d128fa'),
    ],
    category: 'Bags',
    sizes: ['Free Size'],
    colors: [{ name: 'Tan', hex: '#D2B48C' }, { name: 'Black', hex: '#000000' }],
    rating: 4.8,
    reviewCount: 203,
    badges: ['matches-style'],
    stock: 6,
    description: 'Genuine leather tote with laptop compartment. Elegant enough for office, spacious enough for travel.',
    tags: ['office', 'travel', 'bag', 'leather'],
  },
  {
    id: 'p12',
    name: 'Printed Coord Set',
    brand: 'AND',
    price: 2799,
    originalPrice: 3999,
    discount: 30,
    images: [
      UNSPLASH('photo-1512436991641-6745cdb1723f'),
      UNSPLASH('photo-1525507119028-ed4c629a60a3'),
    ],
    category: 'Co-ords',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Lilac', hex: '#C8A2C8' }, { name: 'Sage', hex: '#BCB88A' }],
    rating: 4.5,
    reviewCount: 178,
    badges: ['matches-style', 'low-stock'],
    stock: 4,
    description: 'Chic printed coord set for brunches, date nights, and everything in between.',
    tags: ['date-night', 'casual', 'coord', 'printed'],
  },
];

export const getProductById = (id: string) =>
  mockProducts.find((p) => p.id === id) ?? mockProducts[0];

export const getProductsByVibe = (vibe: string): Product[] => {
  const vibeTagMap: Record<string, string[]> = {
    casual: ['casual', 'denim', 'linen'],
    festive: ['festive', 'ethnic', 'silk', 'wedding'],
    office: ['office', 'formal', 'work'],
    'date-night': ['date-night', 'floral', 'dress'],
    gifting: ['leather', 'bag', 'silk'],
    gym: ['gym', 'sport', 'activewear', 'yoga'],
    travel: ['travel', 'casual', 'denim'],
  };
  const tags = vibeTagMap[vibe] ?? [];
  const filtered = mockProducts.filter((p) =>
    p.tags.some((t) => tags.includes(t))
  );
  return filtered.length > 3 ? filtered : mockProducts;
};
